package:
  name: phenocellpy
  version: 0.1.0


about:
  home: https://github.com/OpenVT/PhenoCellPy
  license: BSD 3-Clause License
  license_file: ../LICENSE

extra:
  maintainer: Juliano Ferrari Gianlupi and Dept Intelligent Sys Eng and Biocomplexity Inst, Indiana University, Bloomington, IN
  publication: https://doi.org/10.1101/2023.04.12.535625

source:
  path: ../

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install .package --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
